/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    id: bigint;
    date: bigint;
    name: string;
    description: string;
    isPast: boolean;
    outcomes?: string;
    isPublic: boolean;
    registrationLink?: string;
    photos: Array<ExternalBlob>;
    poster?: ExternalBlob;
}
export interface Collaboration {
    id: bigint;
    contactInfo?: string;
    companyName: string;
    internshipOpportunity?: string;
    isPublic: boolean;
    problemStatement?: string;
}
export interface Registration {
    id: bigint;
    status: string;
    branch: string;
    name: string;
    year: string;
    submittedBy: Principal;
    interestArea: string;
    timestamp: bigint;
    skills: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Achievement {
    id: bigint;
    title: string;
    date: bigint;
    description: string;
    recipients: string;
    category: string;
    isPublic: boolean;
}
export interface GalleryImage {
    id: bigint;
    caption?: string;
    category: string;
    image: ExternalBlob;
    isPublic: boolean;
}
export interface Announcement {
    id: bigint;
    title: string;
    content: string;
    timestamp: bigint;
    category: string;
    isPublic: boolean;
}
export interface TeamMember {
    id: bigint;
    name: string;
    role: string;
    isPublic: boolean;
    photo?: ExternalBlob;
    department: string;
}
export interface Resource {
    id: bigint;
    title: string;
    link: string;
    description: string;
    category: string;
    isPublic: boolean;
}
export interface Project {
    id: bigint;
    techUsed: string;
    title: string;
    submittedBy: Principal;
    description: string;
    demoLink?: string;
    teamMembers: string;
    timestamp: bigint;
    isPublic: boolean;
}
export interface UserProfile {
    branch?: string;
    name: string;
    year?: string;
    skills?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAchievement(title: string, category: string, description: string, date: bigint, recipients: string): Promise<bigint>;
    addCollaboration(companyName: string, problemStatement: string | null, internshipOpportunity: string | null, contactInfo: string | null): Promise<bigint>;
    addResource(title: string, category: string, description: string, link: string): Promise<bigint>;
    addTeamMember(name: string, role: string, department: string, photo: ExternalBlob | null): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEvent(name: string, date: bigint, description: string, photos: Array<ExternalBlob>, outcomes: string | null, registrationLink: string | null, poster: ExternalBlob | null, isPast: boolean): Promise<bigint>;
    deleteAnnouncement(id: bigint): Promise<void>;
    deleteEvent(id: bigint): Promise<void>;
    deleteGalleryImage(id: bigint): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    getAchievementsByCategory(category: string): Promise<Array<Achievement>>;
    getAllPublicAchievements(): Promise<Array<Achievement>>;
    getAllPublicAnnouncements(): Promise<Array<Announcement>>;
    getAllPublicCollaborations(): Promise<Array<Collaboration>>;
    getAllPublicGalleryImages(): Promise<Array<GalleryImage>>;
    getAllPublicProjects(): Promise<Array<Project>>;
    getAllPublicResources(): Promise<Array<Resource>>;
    getAllPublicTeamMembers(): Promise<Array<TeamMember>>;
    getAllRegistrations(): Promise<Array<Registration>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGalleryImagesByCategory(category: string): Promise<Array<GalleryImage>>;
    getMyProjects(): Promise<Array<Project>>;
    getMyRegistration(): Promise<Registration | null>;
    getPastEvents(): Promise<Array<Event>>;
    getResourcesByCategory(category: string): Promise<Array<Resource>>;
    getTeamMember(id: bigint): Promise<TeamMember | null>;
    getTeamMembersByDepartment(department: string): Promise<Array<TeamMember>>;
    getTeamMembersByRole(role: string): Promise<Array<TeamMember>>;
    getUpcomingEvents(): Promise<Array<Event>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    postAnnouncement(title: string, content: string, category: string): Promise<bigint>;
    publishAchievement(id: bigint): Promise<void>;
    publishAnnouncement(id: bigint): Promise<void>;
    publishCollaboration(id: bigint): Promise<void>;
    publishEvent(id: bigint): Promise<void>;
    publishGalleryImage(id: bigint): Promise<void>;
    publishProject(id: bigint): Promise<void>;
    publishResource(id: bigint): Promise<void>;
    publishTeamMember(id: bigint): Promise<void>;
    removeAchievement(id: bigint): Promise<void>;
    removeCollaboration(id: bigint): Promise<void>;
    removeResource(id: bigint): Promise<void>;
    removeTeamMember(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitProject(title: string, description: string, techUsed: string, teamMembers: string, demoLink: string | null): Promise<bigint>;
    submitRegistration(name: string, branch: string, year: string, skills: string, interestArea: string): Promise<bigint>;
    updateAchievement(id: bigint, title: string, category: string, description: string, date: bigint, recipients: string): Promise<void>;
    updateAnnouncement(id: bigint, title: string, content: string, category: string): Promise<void>;
    updateCollaboration(id: bigint, companyName: string, problemStatement: string | null, internshipOpportunity: string | null, contactInfo: string | null): Promise<void>;
    updateEvent(id: bigint, name: string, date: bigint, description: string, photos: Array<ExternalBlob>, outcomes: string | null, registrationLink: string | null, poster: ExternalBlob | null, isPast: boolean): Promise<void>;
    updateProject(id: bigint, title: string, description: string, techUsed: string, teamMembers: string, demoLink: string | null): Promise<void>;
    updateRegistrationStatus(id: bigint, status: string): Promise<void>;
    updateResource(id: bigint, title: string, category: string, description: string, link: string): Promise<void>;
    updateTeamMember(id: bigint, name: string, role: string, department: string, photo: ExternalBlob | null): Promise<void>;
    uploadGalleryImage(category: string, image: ExternalBlob, caption: string | null): Promise<bigint>;
}
import type { Collaboration as _Collaboration, Event as _Event, ExternalBlob as _ExternalBlob, GalleryImage as _GalleryImage, Project as _Project, Registration as _Registration, TeamMember as _TeamMember, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAchievement(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addCollaboration(arg0: string, arg1: string | null, arg2: string | null, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollaboration(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollaboration(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addResource(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTeamMember(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamMember(arg0, arg1, arg2, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamMember(arg0, arg1, arg2, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: string, arg1: bigint, arg2: string, arg3: Array<ExternalBlob>, arg4: string | null, arg5: string | null, arg6: ExternalBlob | null, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getAchievementsByCategory(arg0: string): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievementsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievementsByCategory(arg0);
            return result;
        }
    }
    async getAllPublicAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicAchievements();
            return result;
        }
    }
    async getAllPublicAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicAnnouncements();
            return result;
        }
    }
    async getAllPublicCollaborations(): Promise<Array<Collaboration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicCollaborations();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicCollaborations();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicGalleryImages();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicGalleryImages();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicProjects();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicProjects();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicResources();
            return result;
        }
    }
    async getAllPublicTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicTeamMembers();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicTeamMembers();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRegistrations(): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistrations();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImagesByCategory(arg0: string): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImagesByCategory(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImagesByCategory(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProjects();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProjects();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRegistration(): Promise<Registration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRegistration();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRegistration();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPastEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPastEvents();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPastEvents();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesByCategory(arg0: string): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesByCategory(arg0);
            return result;
        }
    }
    async getTeamMember(arg0: bigint): Promise<TeamMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMember(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMember(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMembersByDepartment(arg0: string): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembersByDepartment(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembersByDepartment(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMembersByRole(arg0: string): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembersByRole(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembersByRole(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postAnnouncement(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.postAnnouncement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postAnnouncement(arg0, arg1, arg2);
            return result;
        }
    }
    async publishAchievement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishAchievement(arg0);
            return result;
        }
    }
    async publishAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishAnnouncement(arg0);
            return result;
        }
    }
    async publishCollaboration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishCollaboration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishCollaboration(arg0);
            return result;
        }
    }
    async publishEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishEvent(arg0);
            return result;
        }
    }
    async publishGalleryImage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishGalleryImage(arg0);
            return result;
        }
    }
    async publishProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishProject(arg0);
            return result;
        }
    }
    async publishResource(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishResource(arg0);
            return result;
        }
    }
    async publishTeamMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishTeamMember(arg0);
            return result;
        }
    }
    async removeAchievement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAchievement(arg0);
            return result;
        }
    }
    async removeCollaboration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCollaboration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCollaboration(arg0);
            return result;
        }
    }
    async removeResource(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeResource(arg0);
            return result;
        }
    }
    async removeTeamMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTeamMember(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProject(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProject(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitRegistration(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistration(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistration(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateAchievement(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAchievement(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAchievement(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateAnnouncement(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateCollaboration(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollaboration(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollaboration(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: Array<ExternalBlob>, arg5: string | null, arg6: string | null, arg7: ExternalBlob | null, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateRegistrationStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistrationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistrationStatus(arg0, arg1);
            return result;
        }
    }
    async updateResource(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResource(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResource(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateTeamMember(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0, arg1, arg2, arg3, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0, arg1, arg2, arg3, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async uploadGalleryImage(arg0: string, arg1: ExternalBlob, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadGalleryImage(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadGalleryImage(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Collaboration_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collaboration): Collaboration {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_Event_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryImage_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): Promise<GalleryImage> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_TeamMember_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): Promise<TeamMember> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Registration]): Registration | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMember]): Promise<TeamMember | null> {
    return value.length === 0 ? null : await from_candid_TeamMember_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactInfo: [] | [string];
    companyName: string;
    internshipOpportunity: [] | [string];
    isPublic: boolean;
    problemStatement: [] | [string];
}): {
    id: bigint;
    contactInfo?: string;
    companyName: string;
    internshipOpportunity?: string;
    isPublic: boolean;
    problemStatement?: string;
} {
    return {
        id: value.id,
        contactInfo: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.contactInfo)),
        companyName: value.companyName,
        internshipOpportunity: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.internshipOpportunity)),
        isPublic: value.isPublic,
        problemStatement: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.problemStatement))
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    caption: [] | [string];
    category: string;
    image: _ExternalBlob;
    isPublic: boolean;
}): Promise<{
    id: bigint;
    caption?: string;
    category: string;
    image: ExternalBlob;
    isPublic: boolean;
}> {
    return {
        id: value.id,
        caption: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.caption)),
        category: value.category,
        image: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.image),
        isPublic: value.isPublic
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    techUsed: string;
    title: string;
    submittedBy: Principal;
    description: string;
    demoLink: [] | [string];
    teamMembers: string;
    timestamp: bigint;
    isPublic: boolean;
}): {
    id: bigint;
    techUsed: string;
    title: string;
    submittedBy: Principal;
    description: string;
    demoLink?: string;
    teamMembers: string;
    timestamp: bigint;
    isPublic: boolean;
} {
    return {
        id: value.id,
        techUsed: value.techUsed,
        title: value.title,
        submittedBy: value.submittedBy,
        description: value.description,
        demoLink: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.demoLink)),
        teamMembers: value.teamMembers,
        timestamp: value.timestamp,
        isPublic: value.isPublic
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: string;
    isPublic: boolean;
    photo: [] | [_ExternalBlob];
    department: string;
}): Promise<{
    id: bigint;
    name: string;
    role: string;
    isPublic: boolean;
    photo?: ExternalBlob;
    department: string;
}> {
    return {
        id: value.id,
        name: value.name,
        role: value.role,
        isPublic: value.isPublic,
        photo: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.photo)),
        department: value.department
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: [] | [string];
    name: string;
    year: [] | [string];
    skills: [] | [string];
}): {
    branch?: string;
    name: string;
    year?: string;
    skills?: string;
} {
    return {
        branch: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.branch)),
        name: value.name,
        year: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.year)),
        skills: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.skills))
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: bigint;
    name: string;
    description: string;
    isPast: boolean;
    outcomes: [] | [string];
    isPublic: boolean;
    registrationLink: [] | [string];
    photos: Array<_ExternalBlob>;
    poster: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    date: bigint;
    name: string;
    description: string;
    isPast: boolean;
    outcomes?: string;
    isPublic: boolean;
    registrationLink?: string;
    photos: Array<ExternalBlob>;
    poster?: ExternalBlob;
}> {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        description: value.description,
        isPast: value.isPast,
        outcomes: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.outcomes)),
        isPublic: value.isPublic,
        registrationLink: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.registrationLink)),
        photos: await from_candid_vec_n38(_uploadFile, _downloadFile, value.photos),
        poster: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.poster))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Collaboration>): Array<Collaboration> {
    return value.map((x)=>from_candid_Collaboration_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Promise<Array<GalleryImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryImage_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n23(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Promise<Array<TeamMember>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TeamMember_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n36(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch?: string;
    name: string;
    year?: string;
    skills?: string;
}): {
    branch: [] | [string];
    name: string;
    year: [] | [string];
    skills: [] | [string];
} {
    return {
        branch: value.branch ? candid_some(value.branch) : candid_none(),
        name: value.name,
        year: value.year ? candid_some(value.year) : candid_none(),
        skills: value.skills ? candid_some(value.skills) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
