/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'recipients' : IDL.Text,
  'category' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const Collaboration = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Opt(IDL.Text),
  'companyName' : IDL.Text,
  'internshipOpportunity' : IDL.Opt(IDL.Text),
  'isPublic' : IDL.Bool,
  'problemStatement' : IDL.Opt(IDL.Text),
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'caption' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'isPublic' : IDL.Bool,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'techUsed' : IDL.Text,
  'title' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'demoLink' : IDL.Opt(IDL.Text),
  'teamMembers' : IDL.Text,
  'timestamp' : IDL.Int,
  'isPublic' : IDL.Bool,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isPublic' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
  'department' : IDL.Text,
});
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'branch' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'interestArea' : IDL.Text,
  'timestamp' : IDL.Int,
  'skills' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'branch' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'year' : IDL.Opt(IDL.Text),
  'skills' : IDL.Opt(IDL.Text),
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPast' : IDL.Bool,
  'outcomes' : IDL.Opt(IDL.Text),
  'isPublic' : IDL.Bool,
  'registrationLink' : IDL.Opt(IDL.Text),
  'photos' : IDL.Vec(ExternalBlob),
  'poster' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAchievement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addCollaboration' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getAchievementsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'getAllPublicAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAllPublicAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getAllPublicCollaborations' : IDL.Func(
      [],
      [IDL.Vec(Collaboration)],
      ['query'],
    ),
  'getAllPublicGalleryImages' : IDL.Func(
      [],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getAllPublicProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllPublicResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllPublicTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryImagesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getMyRegistration' : IDL.Func([], [IDL.Opt(Registration)], ['query']),
  'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getResourcesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getTeamMember' : IDL.Func([IDL.Nat], [IDL.Opt(TeamMember)], ['query']),
  'getTeamMembersByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeamMember)],
      ['query'],
    ),
  'getTeamMembersByRole' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeamMember)],
      ['query'],
    ),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'publishAchievement' : IDL.Func([IDL.Nat], [], []),
  'publishAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'publishCollaboration' : IDL.Func([IDL.Nat], [], []),
  'publishEvent' : IDL.Func([IDL.Nat], [], []),
  'publishGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'publishProject' : IDL.Func([IDL.Nat], [], []),
  'publishResource' : IDL.Func([IDL.Nat], [], []),
  'publishTeamMember' : IDL.Func([IDL.Nat], [], []),
  'removeAchievement' : IDL.Func([IDL.Nat], [], []),
  'removeCollaboration' : IDL.Func([IDL.Nat], [], []),
  'removeResource' : IDL.Func([IDL.Nat], [], []),
  'removeTeamMember' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'submitRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateAchievement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCollaboration' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateRegistrationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateResource' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTeamMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'uploadGalleryImage' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'recipients' : IDL.Text,
    'category' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const Collaboration = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Opt(IDL.Text),
    'companyName' : IDL.Text,
    'internshipOpportunity' : IDL.Opt(IDL.Text),
    'isPublic' : IDL.Bool,
    'problemStatement' : IDL.Opt(IDL.Text),
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'caption' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'isPublic' : IDL.Bool,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'techUsed' : IDL.Text,
    'title' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'demoLink' : IDL.Opt(IDL.Text),
    'teamMembers' : IDL.Text,
    'timestamp' : IDL.Int,
    'isPublic' : IDL.Bool,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isPublic' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
    'department' : IDL.Text,
  });
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'branch' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'interestArea' : IDL.Text,
    'timestamp' : IDL.Int,
    'skills' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'branch' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'year' : IDL.Opt(IDL.Text),
    'skills' : IDL.Opt(IDL.Text),
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPast' : IDL.Bool,
    'outcomes' : IDL.Opt(IDL.Text),
    'isPublic' : IDL.Bool,
    'registrationLink' : IDL.Opt(IDL.Text),
    'photos' : IDL.Vec(ExternalBlob),
    'poster' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAchievement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addCollaboration' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getAchievementsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'getAllPublicAchievements' : IDL.Func(
        [],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'getAllPublicAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getAllPublicCollaborations' : IDL.Func(
        [],
        [IDL.Vec(Collaboration)],
        ['query'],
      ),
    'getAllPublicGalleryImages' : IDL.Func(
        [],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getAllPublicProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllPublicResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllPublicTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryImagesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getMyRegistration' : IDL.Func([], [IDL.Opt(Registration)], ['query']),
    'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getResourcesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getTeamMember' : IDL.Func([IDL.Nat], [IDL.Opt(TeamMember)], ['query']),
    'getTeamMembersByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeamMember)],
        ['query'],
      ),
    'getTeamMembersByRole' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeamMember)],
        ['query'],
      ),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'publishAchievement' : IDL.Func([IDL.Nat], [], []),
    'publishAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'publishCollaboration' : IDL.Func([IDL.Nat], [], []),
    'publishEvent' : IDL.Func([IDL.Nat], [], []),
    'publishGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'publishProject' : IDL.Func([IDL.Nat], [], []),
    'publishResource' : IDL.Func([IDL.Nat], [], []),
    'publishTeamMember' : IDL.Func([IDL.Nat], [], []),
    'removeAchievement' : IDL.Func([IDL.Nat], [], []),
    'removeCollaboration' : IDL.Func([IDL.Nat], [], []),
    'removeResource' : IDL.Func([IDL.Nat], [], []),
    'removeTeamMember' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'submitRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateAchievement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCollaboration' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateRegistrationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateResource' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTeamMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'uploadGalleryImage' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };