/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'recipients' : string,
  'category' : string,
  'isPublic' : boolean,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
  'category' : string,
  'isPublic' : boolean,
}
export interface Collaboration {
  'id' : bigint,
  'contactInfo' : [] | [string],
  'companyName' : string,
  'internshipOpportunity' : [] | [string],
  'isPublic' : boolean,
  'problemStatement' : [] | [string],
}
export interface Event {
  'id' : bigint,
  'date' : bigint,
  'name' : string,
  'description' : string,
  'isPast' : boolean,
  'outcomes' : [] | [string],
  'isPublic' : boolean,
  'registrationLink' : [] | [string],
  'photos' : Array<ExternalBlob>,
  'poster' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : bigint,
  'caption' : [] | [string],
  'category' : string,
  'image' : ExternalBlob,
  'isPublic' : boolean,
}
export interface Project {
  'id' : bigint,
  'techUsed' : string,
  'title' : string,
  'submittedBy' : Principal,
  'description' : string,
  'demoLink' : [] | [string],
  'teamMembers' : string,
  'timestamp' : bigint,
  'isPublic' : boolean,
}
export interface Registration {
  'id' : bigint,
  'status' : string,
  'branch' : string,
  'name' : string,
  'year' : string,
  'submittedBy' : Principal,
  'interestArea' : string,
  'timestamp' : bigint,
  'skills' : string,
}
export interface Resource {
  'id' : bigint,
  'title' : string,
  'link' : string,
  'description' : string,
  'category' : string,
  'isPublic' : boolean,
}
export interface TeamMember {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'isPublic' : boolean,
  'photo' : [] | [ExternalBlob],
  'department' : string,
}
export interface UserProfile {
  'branch' : [] | [string],
  'name' : string,
  'year' : [] | [string],
  'skills' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAchievement' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
  'addCollaboration' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string]],
    bigint
  >,
  'addResource' : ActorMethod<[string, string, string, string], bigint>,
  'addTeamMember' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [
      string,
      bigint,
      string,
      Array<ExternalBlob>,
      [] | [string],
      [] | [string],
      [] | [ExternalBlob],
      boolean,
    ],
    bigint
  >,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteGalleryImage' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getAchievementsByCategory' : ActorMethod<[string], Array<Achievement>>,
  'getAllPublicAchievements' : ActorMethod<[], Array<Achievement>>,
  'getAllPublicAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllPublicCollaborations' : ActorMethod<[], Array<Collaboration>>,
  'getAllPublicGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllPublicProjects' : ActorMethod<[], Array<Project>>,
  'getAllPublicResources' : ActorMethod<[], Array<Resource>>,
  'getAllPublicTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryImagesByCategory' : ActorMethod<[string], Array<GalleryImage>>,
  'getMyProjects' : ActorMethod<[], Array<Project>>,
  'getMyRegistration' : ActorMethod<[], [] | [Registration]>,
  'getPastEvents' : ActorMethod<[], Array<Event>>,
  'getResourcesByCategory' : ActorMethod<[string], Array<Resource>>,
  'getTeamMember' : ActorMethod<[bigint], [] | [TeamMember]>,
  'getTeamMembersByDepartment' : ActorMethod<[string], Array<TeamMember>>,
  'getTeamMembersByRole' : ActorMethod<[string], Array<TeamMember>>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postAnnouncement' : ActorMethod<[string, string, string], bigint>,
  'publishAchievement' : ActorMethod<[bigint], undefined>,
  'publishAnnouncement' : ActorMethod<[bigint], undefined>,
  'publishCollaboration' : ActorMethod<[bigint], undefined>,
  'publishEvent' : ActorMethod<[bigint], undefined>,
  'publishGalleryImage' : ActorMethod<[bigint], undefined>,
  'publishProject' : ActorMethod<[bigint], undefined>,
  'publishResource' : ActorMethod<[bigint], undefined>,
  'publishTeamMember' : ActorMethod<[bigint], undefined>,
  'removeAchievement' : ActorMethod<[bigint], undefined>,
  'removeCollaboration' : ActorMethod<[bigint], undefined>,
  'removeResource' : ActorMethod<[bigint], undefined>,
  'removeTeamMember' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProject' : ActorMethod<
    [string, string, string, string, [] | [string]],
    bigint
  >,
  'submitRegistration' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateAchievement' : ActorMethod<
    [bigint, string, string, string, bigint, string],
    undefined
  >,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateCollaboration' : ActorMethod<
    [bigint, string, [] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'updateEvent' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      Array<ExternalBlob>,
      [] | [string],
      [] | [string],
      [] | [ExternalBlob],
      boolean,
    ],
    undefined
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, string, string, [] | [string]],
    undefined
  >,
  'updateRegistrationStatus' : ActorMethod<[bigint, string], undefined>,
  'updateResource' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateTeamMember' : ActorMethod<
    [bigint, string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'uploadGalleryImage' : ActorMethod<
    [string, ExternalBlob, [] | [string]],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];